name: c-42 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: install norminette
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install norminette
    - name: norminette
      run: norminette
#     - name: make
#       run: make
#     - name: make bonus
#       run: make fclean && make bonus
